/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.server;
import java.awt.Color;
import java.io.DataInputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.util.Date;

/**
 *
 * @author OMPRAKASH SEN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    static ServerSocket ss;
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;
    
    public Main() {
        initComponents();
        setResizable(false);
        getContentPane().setBackground(new Color(0,0,0));
        msg_area.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msg_area.setBackground(new java.awt.Color(0, 51, 51));
        msg_area.setColumns(20);
        msg_area.setForeground(new java.awt.Color(255, 255, 255));
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 690, 340));

        msg_text.setBackground(new java.awt.Color(51, 51, 51));
        msg_text.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(msg_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 340, 460, 40));

        send_btn.setBackground(new java.awt.Color(0, 0, 0));
        send_btn.setForeground(new java.awt.Color(255, 255, 255));
        send_btn.setText("SEND");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        getContentPane().add(send_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        String msgout = "";
        try
        {
            msgout = msg_text.getText().trim();
            dos.writeUTF("Server : " + msgout);
        }
        catch(Exception e) {
        }
    }//GEN-LAST:event_send_btnActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
        
        String msgin = "";
        try
        {
         // ss = new ServerSocket(3000);
         ss = new ServerSocket(3000, 1, InetAddress.getLocalHost());
        //InetAddress.getByName("localhost");
        s = ss.accept();
        dis = new DataInputStream(s.getInputStream());
        dos = new DataOutputStream(s.getOutputStream());
        while(true)
        {
            msgin = dis.readUTF();
            msg_area.setText(msg_area.getText().trim()+"\n"+msgin+"  "+new Date());
        }
    }
        catch(Exception e)
        {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JTextField msg_text;
    private javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
